dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 20886
  registry:
    address: zookeeper://127.0.0.1:2181

api:
  env: dev
  register-address: http://127.0.0.1:2379
  registerType: etcd
  type: dubbo
spring:
  main:
    allow-bean-definition-overriding: true

server:
  port: 10000